# Generated by Django 4.2.30 on 2026-04-13 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=1024)),
                ('platform', models.CharField(max_length=50)),
                ('frame_layout', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_pct', models.IntegerField(default=0)),
                ('log', models.TextField(default='')),
                ('error', models.TextField(default='')),
                ('output_dir', models.CharField(default='', max_length=1024)),
                ('meta_path', models.CharField(default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('clip_path', models.CharField(max_length=1024)),
                ('raw_path', models.CharField(default='', max_length=1024)),
                ('thumb_path', models.CharField(default='', max_length=1024)),
                ('image_path', models.CharField(default='', max_length=1024)),
                ('text', models.TextField(default='')),
                ('frame_type', models.CharField(default='torn_card', max_length=50)),
                ('card_params', models.JSONField(default=dict)),
                ('section_pct', models.JSONField(default=dict)),
                ('follow_params', models.JSONField(default=dict)),
                ('split_params', models.JSONField(default=dict)),
                ('preset', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='api.job')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
